### ISSUE TITLE
Please include instructions to install Ansible on clean mac

### ISSUE THREAD

**Issue by dspolleke** [geerlingguy/mac-dev-playbook#100]
On a newly installed mac what is the best way to install ansible? For i can not get it to work. 

python3 -m pip install --upgrade pip 
python3 -m pip install ansible

both fail

sudo -H $HOME python3 -m pip install --upgrade pip 
sudo -H $HOME python3 -m pip instal ansible  

results in a ansible that is not executable for the active user.  (for the python path is owned by root)

**Comment by StephenBrown2** [comment]
You should probably use the `--user` flag. Let us know if the instructions from: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-macos (which point to the real instructions here: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-with-pip ) don't work for you. In particular, pay attention to the NOTE regarding "Running pip with sudo".

**Comment by aussielunix** [comment]
* Upgrade pip
`pip install --upgrade pip`
* Add the following to `~/.bash_profile`
`export PATH="${HOME}/Library/Python/3.8/bin:$PATH"`
* Source the new `.bash_profile`
`source ~/.bash_profile`
* Install Ansible
`pip install ansible`
* Airdrop your ssh key into `~/.ssh` on the new laptop (needed to access private Github repos etc)
  * chmod 0700 ~/.ssh
  * chmod 0400 ~/.ssh/id_rsa
  * chmod 0644 ~/.ssh/id_rsa.pub
* add your ssh-key to keychain
`ssh-add` 
* git clone (your fork of) https://github.com/geerlingguy/mac-dev-playbook to `~/.macup`
  * this may prompt to install command-line-tools if they are not already installed
* install ansible modules etc
`ansible-galaxy install -r requirements.yml`
* airdrop your custom `config.yml` onto new laptop into `~/.macup`
* create an alias for doing ansible runs specific to this repo
`alias macup='ANSIBLE_CONFIG=~/.macup/ansible.cfg ansible-playbook -i ~/.macup/inventory ~/.macup/main.yml -K'`
* run `macup`

**I have written this from memory but I think I have it correct**

**Comment by geerlingguy** [comment]
I have a couple new Macs (M1) I'm testing today, so I hope to get a few of these things cleared up and clarified.

A few quick notes:

  1. Upon initial install, `ansible` will not have libyaml available, so it's a bit slow (3x slower than with it)—see https://github.com/ansible/ansible/issues/72030 — ideally you would install `libyaml` via Homebrew and then later re-install Ansible via Pip (TODO: Add instructions here.).
  2. TODO.

**Comment by geerlingguy** [comment]
Updated terminal profile:

[JJG-Term.terminal.txt](https://github.com/geerlingguy/mac-dev-playbook/files/6543374/JJG-Term.terminal.txt)

Note: I use Consolas on my Mac, but that comes from elsewhere.

**Comment by geerlingguy** [comment]
Also: [Ansible might be running slow if libyaml is not available](https://www.jeffgeerling.com/blog/2021/ansible-might-be-running-slow-if-libyaml-not-available).
