### ISSUE TITLE
Applying Terminal profile fails on remote Macs with defaults

### ISSUE THREAD

**Issue by dspolleke** [geerlingguy/mac-dev-playbook#102]
TASK [Ensure custom Terminal profile is added.] **********************************************************************************************************************************************************
fatal: [re.da.ct.ed]: FAILED! => {"changed": false, "cmd": ["open", "files/terminal/JJG-Term.terminal"], "delta": "0:00:00.038433", "end": "2021-04-06 23:16:37.620269", "msg": "non-zero return code", "rc": 1, "start": "2021-04-06 23:16:37.581836", "stderr": "The file /Users/dspolleke/files/terminal/JJG-Term.terminal does not exist.", "stderr_lines": ["The file /Users/dspolleke/files/terminal/JJG-Term.terminal does not exist."], "stdout": "", "stdout_lines": []}

the tasks
command: open files/terminal/JJG-Term.terminal
obviously cannot open the file on the remote host.

**Comment by geerlingguy** [comment]
I think that task is built in a way that works when running the playbook against localhost. It would be good to make sure it works when running against a remote server via SSH too.

**Comment by dspolleke** [comment]
https://github.com/geerlingguy/mac-dev-playbook/pull/107

fixes this
