### ISSUE TITLE
remap caps-lock to esc

### ISSUE THREAD

**Issue by dspolleke** [geerlingguy/mac-dev-playbook#111]
this can be done by creating a startup item as described here:

https://chuyeow.wtf/2020/06/24/remapping-keys-on-macos

As soon as development restarts on this playbook i will look into creating a pull request for this.

**Comment by geerlingguy** [comment]
Development never ends, it just ebbs and flows as I get closer to buying a new Mac and thus refining it a bit, again. I typically prioritize bugs over new features though, since a lot of people rely on it not breaking (myself included). At least not breaking so bad CI starts failing ;)

**Comment by geerlingguy** [comment]
Closing in favor of older issue that got stale-closed here: https://github.com/geerlingguy/mac-dev-playbook/issues/22
