### ISSUE TITLE
Create new `geerlingguy.mac` collection, include all my Mac-centric roles

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/mac-dev-playbook#116]
I've decided it may be easier to consolidate my Mac-specific roles (`homebrew`, `mas`, and the like) into one collection, where all my Mac-specific testing can also be optimized.

I'd also like to move the `dock` management stuff in this playbook out to that role and clean it up a bit, now that I've had a chance to really wrap my brain around `dockutil`.

And probably also move the `sublime-text.yml` task and associated vars into a separate role there too.

**Comment by dspolleke** [comment]
the problem with dockutil is that you have to know what is there to remove, to be able to remove it. also, the output of dockutil can not be fed back into dockutil .. But if you are turning it into a role, i am happy to help.

**Comment by geerlingguy** [comment]
@dspolleke - That's the intent with that part, to make it so we could maybe add in a custom module or filter or _something_ to make it easier to tame dockutil (e.g. pass the entire array to the module and it sorts things out somehow).

I'm okay with the current implementation, but it does cause Dock to keep restarting while the playbook runs and that looks a little annoying.

**Comment by dspolleke** [comment]
A little? A lot!

**Comment by geerlingguy** [comment]
Working on the structure of the collection here: https://github.com/geerlingguy/ansible-collection-mac

**Comment by geerlingguy** [comment]
Ran into an annoying but in Ansible 2.11 that hopefully has an easy fix: https://github.com/ansible/ansible/issues/74858

**Comment by geerlingguy** [comment]
Collection is created, seems to be working, automated release process is working too (which is nice...).

All that's left is to pull out the dock stuff from this playbook and change it up so it uses the collection!
