### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by mikev1963** [geerlingguy/mac-dev-playbook#124]
Are you using the built-in python from the Mac or Are you installing a later version from Python.org?

**Comment by geerlingguy** [comment]
Built-in for now. But as time goes on (I've been using this playbook in one form or another for 6 years) I go back and forth. Current instructions include:

```
  1. Run the following command to add Python 3 to your $PATH: export PATH="$HOME/Library/Python/3.8/bin:/opt/homebrew/bin:$PATH"
  2. Upgrade Pip: sudo pip3 install --upgrade pip
  3. Install Ansible: pip3 install ansible
```

That uses the built-in version of Python in macOS. But if you're a Python dev and/or like managing Python in other ways, that's fine too.
