### ISSUE TITLE
homebrew parent directory permissions fails 

### ISSUE THREAD

**Issue by TaiSHiNet** [geerlingguy/mac-dev-playbook#126]
Hi,

I couldn't get past homebrew install 

Ansible version: 
```
$ ansible-playbook --version
ansible-playbook [core 2.11.1]
  config file = /Users/taishi/mac-dev-playbook/ansible.cfg
  configured module search path = ['/Users/taishi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/taishi/Library/Python/3.8/lib/python/site-packages/ansible
  ansible collection location = /Users/taishi/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/taishi/Library/Python/3.8/bin/ansible-playbook
  python version = 3.8.2 (default, Apr  8 2021, 23:19:18) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = True
```
Command: 
```
~/Library/Python/3.8/bin/ansible-playbook --ask-become-pass main.yml
```

Error:
```
TASK [geerlingguy.mac.homebrew : Ensure Homebrew parent directory has correct permissions (MacOS >= 10.13).] ************************************************************************
fatal: [127.0.0.1]: FAILED! => changed=false
  module_stderr: |-
    sudo: a password is required
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

All of this on a freshly installed Mac (upgraded to Big Sur)

Thanks in advance,
T

EDIT: removed unnecessary stuff

**Comment by geerlingguy** [comment]
If it's saying `sudo: a password is required`, that seems to indicate maybe you didn't enter your password after running the `--ask-become-pass` password prompt for your user?

Also, the Terminal profile thing could be a separate issue—if you haven't yet opened Terminal on the Mac, then a default profile might not yet be set.

**Comment by TaiSHiNet** [comment]
Using Terminal and first time it ran fine (past that item). I've used `--ask-become-pass` and I've typed it (initially thought this might've been the issue).
What's the terminal profile issue that might be affecting?

**Comment by TaiSHiNet** [comment]
Edited initial message, first time it ran with no config.yml.
Either way, after a fresh format+install I now get the same permission error.
Tried:
* Sudoing with same password (works)
* Putting a wrong/empty password on become pass (to force it to fail)

I got it to work by sudoing and executing the ansible-playbook command within the sudo timeout window

**Comment by JPry** [comment]
I'm seeing this same issue as well. I'm running Ansible from my older computer, and I added the new machine to the inventory file. I can `ssh` to the machine via the terminal without issue. I've definitely entered the correct password for the account (copy/pasted from a password manager), but I still get an error on the "Ensure Homebrew parent directory has correct permissions" task. 

```
ansible-playbook --version
ansible-playbook [core 2.11.2] 
  config file = /Users/jpry/projects/mac-dev-playbook/ansible.cfg
  configured module search path = ['/Users/jpry/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.1.0/libexec/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/jpry/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.5 (default, May  4 2021, 03:33:11) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.1
  libyaml = True
```

```
ansible-playbook --ask-become-pass --tags "homebrew" main.yml
BECOME password: 

PLAY [all] *******************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************************************************************************
[WARNING]: Platform darwin on host a8c-2021-imac.local is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible/2.11/reference_appendices/interpreter_discovery.html for more
information.
ok: [a8c-2021-imac.local]

TASK [Include playbook configuration.] ***************************************************************************************************************************************************************************************************************************************************************************************
ok: [a8c-2021-imac.local] => (item=/Users/jpry/projects/mac-dev-playbook/config.yml)

TASK [geerlingguy.mac.homebrew : Determine Homebrew ownership variables] *****************************************************************************************************************************************************************************************************************************************************
ok: [a8c-2021-imac.local]

TASK [geerlingguy.mac.homebrew : Ensure Homebrew parent directory has correct permissions (MacOS >= 10.13).] *****************************************************************************************************************************************************************************************************************
fatal: [a8c-2021-imac.local]: FAILED! => 
  msg: Missing sudo password

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************************************************************
a8c-2021-imac.local        : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by geerlingguy** [comment]
See also: https://github.com/geerlingguy/ansible-role-homebrew/issues/96

**Comment by JPry** [comment]
> See also: [geerlingguy/ansible-role-homebrew#96](https://github.com/geerlingguy/ansible-role-homebrew/issues/96)

@geerlingguy I'm using `--ask-become-pass`, and still having an issue. Do you have any suggestions? I'm thinking I might just clone the repo on the new machine and run it locally to see if that works, but that shouldn't be necessary with Ansible.

**Comment by JPry** [comment]
With some further digging, it seems that this might be an issue with Ansible itself. When I use the command line option `--ask-become-pass`, then it seems that the password isn't sent over properly. But when I modify the `inventory` file to include `ansible_become_pass='<password>'`, then suddenly sudo starts working.

@geerlingguy I know it's not your responsibility, but would you be able to point me in the right directory for filing an issue in the correct place? Is the ansible/ansible repo the best place for that?

**Comment by jasonheecs** [comment]
I'm running into this same issue on macOS 10.15.7 as well. Ansible version 2.11.2.

**Comment by Mathobal** [comment]
> With some further digging, it seems that this might be an issue with Ansible itself. When I use the command line option `--ask-become-pass`, then it seems that the password isn't sent over properly. But when I modify the `inventory` file to include `ansible_become_pass='<password>'`, then suddenly sudo starts working.

+1 this, same problem with same fix. The osx-cli-tools install before it works fine, however - is the password somehow losing scope as it dives into the collection that provides the homebrew install? Agree, feels like a possible upstream bug.

**Comment by noorul** [comment]
I faced this today. Running `sudo` command to cache password helped.

**Comment by toby-griffiths** [comment]
I also had this issue, but I'm connecting to a remote machine.  I ended up using `ansible_sudo_pass` (might be the same as `ansible_become_pass`?)  passed as an env var on the command line…

    $ ansible-playbook main.yml -e "ansible_become_pass=$SUDO_PW"

**Comment by noorul** [comment]
@toby-griffiths I am running locally.

**Comment by toby-griffiths** [comment]
I can't find a bug on the https://github.com/ansible/ansible issues.  Is this the correct place?  I'm happy to raise it there if it is.

**Comment by fbsb** [comment]
Hi, I just stumbled upon this issue and did some debugging.

It seems to be caused by the role `geerlingguy.mac.homebrew` setting `ansible_become_password: ""` in defaults/main.yml which overwrites the value set by the become plugin as when run with `-K/--ask-become-pass`. 

Setting the password as a cli argument as with `-e ansible_become_pass=$PASSWORD` works because variables passed as cli arguments take precedence over variables defined/set anywhere else.

Unfortunately AFAICT the `ansible_become_password` variable is not available to the task when gathered by the become plugin so it must be explicitly set.

The way I work around this issue in my own playbook (which uses the `geerlingguy.mac` collection) is by prompting for the `ansible_become_pass` variable in the playbook instead of using `-K/--ask-become-pass` which then sets the variable used by the become plugin and by the `Install configured cask applications.` task.

My playbook then looks something like this:
```
---
- hosts: all
  strategy: debug
  vars_prompt:
    - name: ansible_become_password
      prompt: "BECOME password:"

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
```

and is run with `ansible-playbook main.yml`.

Hope this helps.

**Comment by TaiSHiNet** [comment]
Hi @fbsb it does help indeed. 
The setting `ansible_become_password: ""` in the defaults is unneeded, as the variable is already defaulted to empty by Ansible.
I've removed the line from my local copy and it worked with -K
```
$ ansible-playbook -i inventory main.yml --tags homebrew -K
BECOME password:

PLAY [all] ***************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************************
[WARNING]: Platform darwin on host 127.0.0.1 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible/2.11/reference_appendices/interpreter_discovery.html for more information.
ok: [127.0.0.1]

TASK [Include playbook configuration.] ***********************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => (item=/Users/taishi/mac-dev-playbook/config.yml)

TASK [geerlingguy.mac.homebrew : Determine Homebrew ownership variables] *************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.mac.homebrew : Ensure Homebrew parent directory has correct permissions (MacOS >= 10.13).] *************************************************************************************************************************************************
ok: [127.0.0.1]
```

I've filed https://github.com/geerlingguy/ansible-collection-mac/pull/13 to address this, feel free to comment or decline

Thanks for looking into the issue @fbsb 
Bests,
T

**Comment by noorul** [comment]
I wonder how this works in the CI system

**Comment by geerlingguy** [comment]
@TaiSHiNet - Ah, so in that case, maybe we can just comment that line in the `defaults/main.yml` and then the user could specify it if absolutely necessary.

**Comment by geerlingguy** [comment]
Oops, hit close instead of Comment :D
