### ISSUE TITLE
Unable to use -K when connecting to a remote machine

### ISSUE THREAD

**Issue by toby-griffiths** [geerlingguy/mac-dev-playbook#129]
Hi there,

I'm trying to use this awesome project (BIG THANK YOU!) to setup a remote Mac, however I've been unable to get it to work using the `-K` flag for the sudo password, as it reported…

```
TASK [geerlingguy.mac.homebrew : Ensure Homebrew parent directory has correct permissions (MacOS >= 10.13).] *****************************
fatal: [marvin]: FAILED! =>
  msg: Missing sudo password
```

I was finally able to get it working by setting the p/w in an env var (don't worry, I did it via a sourced file), and then running…

```shell
$ ansible-playbook main.yml -e "ansible_sudo_pass=$SUDO_PW"
```

Do you have any idea why this might be?  I've also had to specify the `ansible_user` in the inventory.  Could this be related, do you know?…

```
[all]
marvin ansible_user=toby
```

**Comment by geerlingguy** [comment]
Related? https://github.com/geerlingguy/mac-dev-playbook/issues/126

Seems like it could be a bug in Ansible/the homebrew plugin.

**Comment by toby-griffiths** [comment]
Wow.  That was quick!  And now I feel like a fool for not finding that issue first.  Sorry 😓

It does appear to be related.  I'll close this issue.
