### ISSUE TITLE
Workaround for already installed apps

### ISSUE THREAD

**Issue by mplacona** [geerlingguy/mac-dev-playbook#130]
Hey Jeff, thank you so much for sharing this. I saw your video and it felt like a good opportunity to create one for my needs. I love the idea of it being idempotent but I was wondering if there's a way to make the errors go away when a homebrew package is already installed. 

Here's an example of the error I see:

```
failed: [127.0.0.1] (item=firefox) => changed=false
  ansible_loop_var: item
  item: firefox
  msg: 'Error: It seems there is already an App at ''/Applications/Firefox.app''.'
```

It doesn't stop the automation from running but it takes a while to go through and for the script to realise it's going to throw an error.

**UPDATE**: Upon further trial and error, I realised that happens when something has already been installed but not via homebrew.

Thanks again!

**Comment by toby-griffiths** [comment]
@mplacona I don't think it throws that error when brew installed the app in the first place.  Do you already have Firefox installed via a non-brew method?

**Comment by mplacona** [comment]
> @mplacona I don't think it throws that error when brew installed the app in the first place. Do you already have Firefox installed via a non-brew method?

You're totally right! And I'm also thinking this is a homebrew error rather than from this playbook. I wonder if there's a way to "fail silently" in that case? I'm an Ansible newbie.

**Comment by toby-griffiths** [comment]
Glad I could help.  I'm not sure you'd want to fail silently, as ansible has not done what it's been asked to do.

You could add a preceding task to your playbook that, if it detects an existing app, either…

1. removes the cask from the list of apps to install;
2. removes the existing app, allowing Ansible to install the new version;

I would imagine, however, most people will use this script to provision a fresh build, and to keep up-to-date, so it's unlikely to cause too many problems in that scenario.

**Comment by geerlingguy** [comment]
Yeah, to be honest I'm not sure what the best solution would be; for now, I guess I would recommend having your `config.yml` file have something that's already installed in your list of casks, but commented out maybe with a note like "uncomment when installing fresh" or something like that.

**Comment by mplacona** [comment]
Yeah, I guess that will work well. 

Thanks
