### ISSUE TITLE
Shouldn't homebrew role upgrade to latest packages?

### ISSUE THREAD

**Issue by noorul** [geerlingguy/mac-dev-playbook#133]
I was under the impression that homebrew role will ensure that the latest version is installed. Am I missing something?

**Comment by dhoppe** [comment]
It looks like you need to set the parameter homebrew_upgrade_all_packages to true:
* https://github.com/geerlingguy/ansible-collection-mac/blob/ee75bb06dc3776d7f57be00eebf7132c06eec7ef/roles/homebrew/defaults/main.yml#L12
* https://github.com/geerlingguy/ansible-collection-mac/blob/ee75bb06dc3776d7f57be00eebf7132c06eec7ef/roles/homebrew/tasks/main.yml#L136

**Comment by noorul** [comment]
Thank you @dhoppe . I will try that.
