### ISSUE TITLE
Any Idea why cloning dotfiles repo task fails?

### ISSUE THREAD

**Issue by Moghi** [geerlingguy/mac-dev-playbook#134]
Hi,

When I reach the task that downloads the dotfiles repo, the task fails with
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
when I clone the repo manually it works. Any idea whats wrong?

More details on [stackoverflow post](https://stackoverflow.com/q/68458086/4457885)

**Comment by geerlingguy** [comment]
@Moghi - The default is to clone from an https repo (https://github.com/geerlingguy/mac-dev-playbook/blob/master/default.config.yml#L27), to avoid this issue. If you clone with git@github.com, then you have to make sure you have your SSH key available somehow (e.g. via `ssh-agent`).
