### ISSUE TITLE
Username jgeerling is hardcoded in main playbook

### ISSUE THREAD

**Issue by wilsonmar** [geerlingguy/mac-dev-playbook#14]
The file now starts with:

```
---
- hosts: localhost
  user: jgeerling
```
Should we change "jgeerling" to our my own Mac account name?

**Comment by geerlingguy** [comment]
Ah yes... I should probably make that configurable or change the way that works :)

**Comment by fubarhouse** [comment]
I've made my own little variation for another purpose, and removing it did the trick for me.
