### ISSUE TITLE
Ensure custom Terminal profile is added - bombs

### ISSUE THREAD

**Issue by patrckb** [geerlingguy/mac-dev-playbook#140]
Environment: Fresh install of macOS Monterey in VirtualBox machine.

Running the playbook goes fine until it gets to the section:
```
- name: Ensure custom Terminal profile is added.
  command: open /tmp/JJG-Term.terminal
  changed_when: false
  when: "'JJG-Term' not in terminal_theme.stdout"
```
I get a popup error: 
`“JJG-Term.terminal” cannot be opened because it is from an unidentified developer.`

I googled for an answer and manually did:

`% xattr -d com.apple.quarantine /tmp/JJG-Term.terminal`

I restarted the playbook and it successfully finished!
[In my best Skip Cary voice, "How About That!"]

Is there a way to have Ansible do the `xattr` command in the playbook?

**Comment by geerlingguy** [comment]
Hmm... that stinks. Didn't realize terminal profiles have to be signed!

**Comment by Drallas** [comment]
> Hmm... that stinks. Didn't realize terminal profiles have to be signed!

But JJG-Term.terminal is yours JJG, I exported my own profile and placed it in files/terminal and changed  JJG-Term.terminal to drallas.terminal did see any error and profile is added to Terminal. 

Unfortunately setting the profile to **default** also isn't working in Monterey. Trying to find out if there is some another file involved but no success yet. 

```
# TODO: This doesn't work in Yosemite. Consider a different solution?
- name: Ensure custom Terminal profile is set as default.
```

**Comment by Drallas** [comment]
@geerlingguy Default Profile is set correctly after I run the terminal task, but need to restart the Terminal for it to become active. 

Added this to the playbook to force the profile active. 

```
- name: Restart Terminal to activate new profile.
  shell: | 
    osascript -e 'quit app "Terminal"'
    open -a Terminal
  changed_when: false
  when: "'drallas' not in terminal_theme.stdout"
```

Made a PR reflecting this change https://github.com/geerlingguy/mac-dev-playbook/pull/141

**Comment by Drallas** [comment]
> Is there a way to have Ansible do the `xattr` command in the playbook?

Perhaps consider creating your own Custom Profile; works for me! 😇
