### ISSUE TITLE
Feature request: command(s) to compare and add already-installed items from (1) mas list and (2) brew list into config.yml

### ISSUE THREAD

**Issue by philCryoport** [geerlingguy/mac-dev-playbook#142]
Hi there,

* As a:
  * mac-dev-playbook user 
  * on a MacOS computer that meets the minimum requirements for mac-dev-playbook
  * with any of the following:
    * (a) mas_installed_apps listed in my config.yml 
    * and/or 
    * (b) apps already installed on the computer from the Mac App Store
* I would like: 
  * to be able to ask mac-dev-playbook to generate a gap-analysis report comparing 
    * (a) the config.yml mas_installed_apps list of Mac App Store applications 
    * versus 
    * (b) what's actually installed on that MacOS computer from the Mac App Store
* So that:
   * I can see what -- if any -- Mac App Store applications I might want to add to my config.yml
(extra kudos awarded if user is then provided a UI at that moment to pick items for mac-dev-playbook would then add to the config.yml)

* As a:
  * mac-dev-playbook user 
  * on a MacOS computer that meets the minimum requirements for mac-dev-playbook
  * with any of the following:
    * (a) homebrew_installed_packages listed in my config.yml 
    * and/or 
    * (b) homebrew_taps listed in my config.yml 
    * and/or
    * (c) homebrew_cask_apps listed in my config.yml 
    * and/or
    * (d) Homebrew packages, taps, and casks already-installed on the computer
* I would like: 
  * to be able to ask mac-dev-playbook to generate a gap-analysis report comparing 
    * (a) the config.yml homebrew_installed_packages, homebrew_taps, and homebrew_cask_apps lists of Homebrew packages, taps, and casks 
    * versus 
    * (b) what's already-installed-via / already-configured-in Homebrew on that MacOS computer as a Homebrew package, tap, and/or cask
* So that:
   * I can see what -- if any -- Homebrew packages, taps, and/or taps I might want to add to my config.yml
(extra kudos awarded if user is then provided a UI at that moment to pick items for mac-dev-playbook would then add to the config.yml)

**Comment by geerlingguy** [comment]
I know there are commands like `mas list` that will grab a listing out for you, and with Homebrew, it's like `brew list installed`(?) — I don't think I'd build any kind of fancy scripts or UIs to do all the work of formatting it into a valid config.yml file, but I think someone else has done some of that work previously in another issue.
