### ISSUE TITLE
Cask package failing because of svn

### ISSUE THREAD

**Issue by clyra** [geerlingguy/mac-dev-playbook#149]
Hi,

My (almost) unattended Mac install is failing because one cask package requires the svn command. Here's the error:

```
failed: [127.0.0.1] (item=font-fira-mono-for-powerline) => changed=false 
  ansible_loop_var: item
  item: font-fira-mono-for-powerline
  msg: |-
    You must: brew install svn
    Error: Download failed on Cask 'font-fira-mono-for-powerline' with message: Failure while executing; `svn checkout https://github.com/powerline/fonts/trunk/FiraMono /Users/lyra/Library/Caches/Homebrew/Cask/font-fira-mono-for-powerline--svn --quiet` exited with 1. Here's the output:
    You must: brew install svn
```

Adding svn to the homebrew packages doesn't work because the task with cask packages fails, and the brew packages task doesn't get a chance to run. One possible ease fix is to call the brew packages task before the cask one ?

**Comment by mAAdhaTTah** [comment]
I also ran into this trying to migrate from a customer homebrew role to this role.

**Comment by mitdemrad** [comment]
I also just ran into this problem while trying to install a cask font.

**Comment by geerlingguy** [comment]
Can you give an example of one of the packages that fails to install? Is it just `font-fira-mono-for-powerline`?

**Comment by clyra** [comment]
I use very few fonts, but fails with these too:

- font-hack-nerd-font
- font-meslo-lg-nerd-font

I did a quick grep inside de homebrew folder and found various references to svn like these:

Library/Taps/homebrew/homebrew-cask-fonts/Casks/font-athiti.rb:      using:    :svn
Library/Taps/homebrew/homebrew-cask-fonts/Casks/font-tsukimi-rounded.rb:      using:    :svn
Library/Taps/homebrew/homebrew-cask-fonts/Casks/font-zilla-slab-highlight.rb:      using:    :svn
Library/Taps/homebrew/homebrew-cask-fonts/Casks/font-monofur-for-powerline.rb:      using: :svn
Library/Taps/homebrew/homebrew-cask-fonts/Casks/font-the-nautigal.rb:      using:    :svn

maybe this a kind of pattern to download fonts.

**Comment by christianarty** [comment]
Also, I encountered this issue with `font-source-code-pro`
