### ISSUE TITLE
I've started making commits as Jeff Geerling after using this...

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/mac-dev-playbook#15]
You might want to fix up the ~/.gitconfig file somewhere here, because I've just made a commit in your repositories in your name accidentally.

**Comment by geerlingguy** [comment]
Hehe, that's just my strategy to take over all the world's commit history ;)

**Comment by geerlingguy** [comment]
For dotfile configuration, you should override the `dotfiles_files` variable and remove the .gitignore (and any other file you don't want placed—or even override the repo as well, if you have your own dotfiles somewhere accessible via git.

**Comment by geerlingguy** [comment]
I might eventually follow the same setup I use with Drupal VM where you could override things with a `local.config.yml` or `config.yml` file, something like that... that way I could still keep the defaults but recommend users of this playbook at least override the basics in that file.

**Comment by bhasselbeck** [comment]
Hahaha, this is the best/craziest bug ever.  I did the same just now.  I wonder if there's a more apparent way to fix this so the end user doesn't have to do any config of that sort.

**Comment by geerlingguy** [comment]
@bhasselbeck - I could just default to excluding the `.gitconfig` file... I think that's safer (though I'll lose some of my awesome Git commit credit karma!).
