### ISSUE TITLE
Is it possible to configure this playbook to install and configure VS code?

### ISSUE THREAD

**Issue by ivan-srsen** [geerlingguy/mac-dev-playbook#158]

**Comment by AlexNabokikh** [comment]
To install VSCode you can add the next line to your config.yml:
```yaml
homebrew_cask_apps:
  - visual-studio-code
```
As for configuration, it is better to configure your VSCode and then use automatic sync via GitHub gist. All you need is to enable this function as below:
<img width="313" alt="image" src="https://user-images.githubusercontent.com/42908293/180944454-7bb22b8e-ccf4-4e5a-9637-8efac7fc0d7c.png">

**Comment by ivan-srsen** [comment]
My plan is to make an installer so that company newcomers can share it. Will automatic sync work like that?

**Comment by AlexNabokikh** [comment]
If I get what I think you mean, then you won't be able to achieve this without forking and expanding the functionality of this playbook. You can try to create an additional task where you generate settings.json for VSCode using the jinja2 template.
The VSCode sync won't work here as it is bound to a GitHub user account unless you want to use one account for all your users. It is a terrible idea if you ask me, as well as forcing your users to use the same settings in VSCode. It is much better to install VSCode on managed machines and let users figure out their settings.

**Comment by ivan-srsen** [comment]
Yes, I agree. I think I'll just make vscode installation along with some predefined extensions we use.
