### ISSUE TITLE
Question about standard practice of getting around issue.

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/mac-dev-playbook#18]
Having some trouble getting a success on three casks, I'm just wondering what the standard practice on resolving this problem is? I've tried a lot of things so far and so far nothing has fixed it.

````
failed: [127.0.0.1] (item=adobe-creative-cloud) => {"changed": true, "cmd": ["bash", "-l", "-c", "/usr/local/bin/brew cask install adobe-creative-cloud --appdir=/Applications"], "delta": "0:00:05.343239", "end": "2016-09-25 00:36:41.952803", "failed": true, "item": "adobe-creative-cloud", "rc": 1, "start": "2016-09-25 00:36:36.609564", "stderr": "Error: Failed to eject /private/tmp/dmg.JZOyio", "stdout": "==> Downloading https://ccmdls.adobe.com/AdobeProducts/KCCC/1/osx10/CreativeCloudInstaller.dmg\n==> No checksum defined for Cask adobe-creative-cloud, skipping verification", "stdout_lines": ["==> Downloading https://ccmdls.adobe.com/AdobeProducts/KCCC/1/osx10/CreativeCloudInstaller.dmg", "==> No checksum defined for Cask adobe-creative-cloud, skipping verification"], "warnings": []}
````

**Comment by geerlingguy** [comment]
It looks like the actual problem is:

```
Error: Failed to eject /private/tmp/dmg.JZOyio
```

It may be related to https://github.com/caskroom/homebrew-cask/issues/13402, but I imagine it would be best to ask about it in the cask issue queue... I install CC manually because it does weird things like this :P

**Comment by fubarhouse** [comment]
I do occasionally get fails on dropbox, adobe-creative-cloud and teamviewer...
It's annoying, but I agree on the manual install alternative... Thanks for the response.
