### ISSUE TITLE
Discussions are disabled for this project on github repo

### ISSUE THREAD

**Issue by cheema-corellian** [geerlingguy/mac-dev-playbook#193]
I recently started playing with Ansible and this playbook.  This is all very exciting.  However, as a new users I do have a few questions about this playbook and I think it would be super cool to have discussions enabled for this repo so that people can ask questions of each other.  And share recipes.

**Comment by geerlingguy** [comment]
Ask, and you shall receive! I've enabled Discussions :)

**Comment by cheema-corellian** [comment]
Dang.  That was fast.  Thank you!
