### ISSUE TITLE
mcrypt fails to install on Sanoma

### ISSUE THREAD

**Issue by DonBower** [geerlingguy/mac-dev-playbook#195]
Relative new install of Sanoma (just added Remote Desktop, MS Remote Desktop, VS Code)

followed directions in README.md, took all defaults. The error seems to explain the issue....

```
failed: [127.0.0.1] (item=mcrypt) => changed=false 
  ansible_loop_var: item
  item: mcrypt
  msg: 'Error: mcrypt has been disabled because it does not build from source from Monterey upwards!'
```

**Comment by geerlingguy** [comment]
Can you drop mcrypt from the default config? https://github.com/geerlingguy/mac-dev-playbook/blob/c99ff5da76d7a077494ecb86a58bd5db44df6e70/README.md?plain=1#L127

**Comment by DonBower** [comment]
Well sure.
No errors now, and I don't know the value of this app for me at this time. Thank you.

**Comment by geerlingguy** [comment]
Great! I've removed it from the defaults as it has been deprecated a while anyway.
