### ISSUE TITLE
dockutil not working

### ISSUE THREAD

**Issue by thatnerdnoah** [geerlingguy/mac-dev-playbook#197]
I am farily new to Ansible and this playbook. When the playbook gets to the dockutil section, I get the following error:

`TASK [geerlingguy.mac.dock : Ensure Dock item Sublime Text exists.] ************
fatal: [192.168.64.4]: FAILED! => changed=false 
  cmd: dockutil --add '/Applications/Sublime Text.app/' --label 'Sublime Text'
  msg: '[Errno 2] No such file or directory: b''dockutil'''
  rc: 2
  stderr: ''
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>`

This is using the default config file. Has anyone ran into this issue themselves? I am testing the playbook on a Virtual Machine using Tart, running the playbook off the host machine (not locally on the virtual machine).

**Comment by j0nv0** [comment]
There also seems to be problem with the way `geerlingguy.mac.dock` tries to ensure dockutil is installed.
Since recently, I get the following error, on a previously working setup:

```
TASK [geerlingguy.mac.dock : Install dockutil.] *************
fatal: [127.0.0.1]: FAILED! => changed=false 
  msg: 'Warning: Cask ''dockutil'' is unavailable: ''/opt/homebrew/Library/Taps/hpedrorodrigues/homebrew-tools/Casks/dockutil.rb'' does not exist.'
```

Maybe the Cask was moved?

**Comment by Kylmakalle** [comment]
Yet it's still a valid issue
