### ISSUE TITLE
Automated testing via travis CI

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/mac-dev-playbook#23]
I've been playing around with OSX travis tests lately, and I don't believe it would be overly difficult to implement into mac-dev-playbook.

I don't know if there's any reason it isn't done already as the associated roles have tests attached to them - but is there any particular reason mac-dev-playbook wasn't made with tests in mind?

I'm thinking of doing it myself to my own fork, but I wanted to hear the reasons of decisions and gather all the information before I try it.

**Comment by geerlingguy** [comment]
Eh... https://travis-ci.org/geerlingguy/mac-dev-playbook — it's already working; see https://github.com/geerlingguy/mac-dev-playbook/issues/17 :)

(This was done after I added tests for https://github.com/geerlingguy/ansible-role-homebrew).

**Comment by fubarhouse** [comment]
My mistake :)
