### ISSUE TITLE
Setting the default Terminal theme

### ISSUE THREAD

**Issue by joonasmyhrberg** [geerlingguy/mac-dev-playbook#26]
I have quite a hacky piece of AppleScript I use to set the default terminal theme. It was pulled from some dotfiles/setup repo but I can't remember where so I'm not able to give proper attribution to the original author. I'm not that familiar with Ansible so I can't make a proper pull request, but I'll leave it here in bash form in case you want to integrate it.

```applescript
osascript <<EOD
tell application "Terminal"
	local allOpenedWindows
	local initialOpenedWindows
	local windowID
	set themeName to "Flat" (* Set the name of the theme*)
	(* Store the IDs of all the open terminal windows. *)
	set initialOpenedWindows to id of every window
	(* Open the custom theme so that it gets added to the list
	   of available terminal themes (note: this will open two
	   additional terminal windows). *)
	do shell script "open '$HOME/Desktop/" & themeName & ".terminal'"
	(* Wait a little bit to ensure that the custom theme is added. *)
	delay 1
	(* Set the custom theme as the default terminal theme. *)
	set default settings to settings set themeName
	(* Get the IDs of all the currently opened terminal windows. *)
	set allOpenedWindows to id of every window
	repeat with windowID in allOpenedWindows
		(* Close the additional windows that were opened in order
		   to add the custom theme to the list of terminal themes. *)
		if initialOpenedWindows does not contain windowID then
			close (every window whose id is windowID)
		(* Change the theme for the initial opened terminal windows
		   to remove the need to close them in order for the custom
		   theme to be applied. *)
		else
			set current settings of tabs of (every window whose id is windowID) to settings set themeName
		end if
	end repeat
end tell
EOD
```

**Comment by geerlingguy** [comment]
Thanks! I'd ideally like to find a way to get this done via a pref/setting so it's simpler (this requires an AppleScript to run and interact with the UI, which would be more prone to breakage with new OS releases). But this script could be helpful in the interim regardless.

**Comment by joonasmyhrberg** [comment]
I might have figured out a way to set the theme with command line only.

If you go look at `~/Library/Preferences/com.apple.Terminal.plist`, you can see that it includes all the settings for Terminal, as well as all the theme settings. The file can be edited from command line with `PlistBuddy`.

For example, to set the default theme name to `JJG-Term`:
``` bash
/usr/libexec/PlistBuddy -c "Set :'Default Window Settings' JJG-Term" ~/Library/Preferences/com.apple.Terminal.plist
```

The same idea would apply to setting the theme parameters. I have not tested that in practice, but at least setting the default theme works.

**Comment by callaginn** [comment]
The bash commands below will change the Terminal theme to "Pro". However, you have to manually restart the Terminal TWICE to apply these settings. Also, PlistBuddy isn't required for simple edits like this.
````bash
sudo -u $USER defaults write com.apple.Terminal.plist "Default Window Settings" "Pro"
sudo -u $USER defaults write com.apple.Terminal.plist "Startup Window Settings" "Pro"
````

I personally found that problematic, so wrote a quick Automator app with the applescript at the top of this thread. This allowed me to add the following line to my setup scripts:
`open /Sites/config/templates/install-theme.app`

**Comment by joonasmyhrberg** [comment]
I was just quickly playing around with the settings, and being more familiar with PlistBuddy I used that. Yours is definitely cleaner, though could it be the reason for the two restarts? I remember doing it only once, but I always restart the computer after the setup so I wouldn't have paid much attention to it when testing. And It was on an earlier MacOS version, which I consider more likely.

I'll close this issue since I switched to iTerm2 a while ago.

**Comment by bfdes** [comment]
> It was pulled from some dotfiles/setup repo but I can't remember where so I'm not able to give proper attribution to the original author.

It *looks like* [this](https://github.com/mathiasbynens/dotfiles/blob/master/.macos) is the original repo.

**Comment by cbrunnkvist** [comment]
(for future google-reference) @myyra the restart I believe has to with caching or parsed plists by `cfprefsd`, but I'm just guessing. It used to be a hassle to restart it when editing files with `plutil` - no idea whether either `PlistBuddy` or `defaults` deal with this in a cleaner way / through some system API.
