### ISSUE TITLE
Ensuring homebrew packages are on the path

### ISSUE THREAD

**Issue by matthewcosgrove** [geerlingguy/mac-dev-playbook#27]
I just want to question how getting installed packages on the path is achieved with the default set up. I would have expected either 

- /usr/local/Cellar gets added to the path (i.e. in the [.bash_profile](https://github.com/geerlingguy/dotfiles/blob/master/.bash_profile))

- symlinks are created in /usr/local/bin (i.e. for the homebrew module using state=linked rather than state=present)

I don't see evidence of either, so just wondering what is required to get this playbook working

There is a catch all in the README about brew issues and running brew doctor, so here is the info I see

- Warning: The following directories are not writable: /usr/local/bin (_this is expected as pip was used to install ansible with sudo_)
- Warning: You have unlinked kegs in your Cellar (_could be fixed manually by making /usr/local/bin writable and running brew link for each pkg or alternatively automatically through the roles by updating the "Ensure proper ownership" task to include the user owner/group and configuring the homebrew module to be state=linked_)

That is how I see things at least, but I'm probably missing something so would be happy to be shown the way

**Comment by geerlingguy** [comment]
@matthewcosgrove - Can you post the full output of `brew doctor`? I'm wondering if there's an additional notice above those two warnings, about a command you may need to run.

**Comment by geerlingguy** [comment]
Also, the homebrew role is _supposed_ to be setting proper ownership on `/usr/local/bin` prior to package installation and linking, but maybe it's not...

See: https://github.com/geerlingguy/ansible-role-homebrew/blob/1d701e254b164795a2ee0c0735e1b285a552f4f3/tasks/main.yml#L44-L51

**Comment by matthewcosgrove** [comment]
@geerlingguy I have put the requested info together via screenshots here https://www.evernote.com/l/AG6VCnP8B-ZPEa5qxtZEp4252iT13-O9Mww

**Comment by geerlingguy** [comment]
`brew doctor` mentions `sudo chown -R $(whoami) /usr/local/bin` to fix the linking issue (then you'd have to run `brew link go && brew link ssh-copy-id` to link those two—then the rest of the install should go well.

It seems the permissions aren't properly getting applied through the homebrew playbook (might be a bug there). It may be getting `root` for `whoami`...

**Comment by matthewcosgrove** [comment]
Yes, exactly. I was suggesting above that the manual fix could be applied but also that it can be fixed in the homebrew role with the following change https://github.com/matthewcosgrove/ansible-role-homebrew/commit/debaf60db89d2845e3a874e68b0d906fe404b4d2

**Comment by geerlingguy** [comment]
@matthewcosgrove - Can you propose that as a PR? (Though I would want to make sure that `linked` will also ensure the packages are installed in the first place).

**Comment by matthewcosgrove** [comment]
Yes will submit a PR, it doesn't require `linked` after all

**Comment by matthewcosgrove** [comment]
PR submitted here https://github.com/geerlingguy/ansible-role-homebrew/pull/55

**Comment by geerlingguy** [comment]
Fixed upstream, will tag a new release shortly (after tests pass).
