### ISSUE TITLE
Allow custom osx script

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/mac-dev-playbook#34]
Currently the osx script is hardcoded as `~/.osx --no-restart` while I personally keep it in an `.osx/` subfolder of my dotfiles repo–It would be nice if this was configurable. As you pass arguments to your script maybe just add it an `osx_script` variable?

I dropped a bottle on my laptop during the night and apparently the MacBook 12" isn't as durable as it looks... Once I get my fork of this project set up, and vim configured, I can start pushing PR's for review.

**Comment by geerlingguy** [comment]
> Once I get my fork of this project set up, and vim configured, I can start pushing PR's for review.

And presumably stop dropping things on your laptop 😂

**Comment by oxyc** [comment]
I'm cursed when it comes to the MacBook 12" haha. I've had two stolen and now one broken by a bottle. Let's hope 4th one lasts a bit longer... or at least until they release a 16gb so I'd get an upgrade.

**Comment by geerlingguy** [comment]
Merged via the PR referenced above.
