### ISSUE TITLE
Add composer/npm/gem support

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/mac-dev-playbook#36]
Would you be interested in PR's for supporting installing composer with global packages, ruby gems and npm packages?

For composer we could use `geerlingguy.composer` with something like:

```
composer_keep_updated: true
composer_add_to_path: false
composer_add_project_to_path: false
composer_home_path: '~/.composer'
composer_home_owner: "{{ ansible_env.SUDO_USER | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"
composer_home_group: "staff" # @todo
composer_global_packages:
  - { name: hirak/prestissimo, release: '^0.3' }
  - { name: wp-cli/wp-cli, release: '^1.0' }
  - { name: drush/drush, release: '^8.1' }
```

For NPM and gems, we could probably just rely on the user installing the brew formulas and then use the ansible package modules.

**Comment by oxyc** [comment]
I'm currently relying on #43 and install using these custom tasks:

- npm/gem/pip: https://github.com/oxyc/mac-dev-playbook/blob/master/custom/packages.yml
- vagrant plugins: #44
- composer: https://github.com/oxyc/mac-dev-playbook/blob/master/custom/composer.yml

**Comment by geerlingguy** [comment]
Doesn't Ansible include a `composer` module? http://docs.ansible.com/ansible/composer_module.html

We could just use that the same way as npm/pip/gem, if we want to support most of the major package managers.

**Comment by oxyc** [comment]
True, I've never managed composer through brew though and that was my reason for going with your role instead. Want me to open up a PR for gem/pip/npm/composer or do you prefer that its done using post-provision-tasks in one's fork?

**Comment by geerlingguy** [comment]
Go ahead and do a PR. I think it would be simple enough a nicety to have available (I often need one or two gems, a couple PHP libraries, some things through pip, etc...). And as long as we default everything to `[]` it's no big deal if someone _doesn't_ use something.

**Comment by geerlingguy** [comment]
Done!
