### ISSUE TITLE
remove deprecated homebrew casks from config.yml

### ISSUE THREAD

**Issue by ownsourcing** [geerlingguy/mac-dev-playbook#40]
## issue (minor cleanup)
the following casks have 
- homebrew-dupes has been deprecated
- homebrew-binary
- homebrew-versions

from https://github.com/Homebrew/homebrew-dupes:

> These formulae were those that duplicated software provided by macOS.
> All formulae were migrated to Homebrew/homebrew-core or deleted.

from https://github.com/Homebrew/homebrew-binary

> These formulae were binary installs of software that, for whatever reason, weren't available as source builds.
> This tap was deprecated because Homebrew Cask handles this use-case better. All formulae were migrated to caskroom/homebrew-cask or other taps.

from https://github.com/Homebrew/homebrew-versions

> These formulae provided multiple versions of existing packages or newer versions of packages that were too incompatible to go in homebrew/core.
> This tap was deprecated because homebrew/core has started to support multiple versions. All widely used, buildable formulae were migrated to homebrew/core.
> Learn more about this migration in the Versions documentation.

## proposed solution
[default config](https://github.com/geerlingguy/mac-dev-playbook/blob/master/default.config.yml) should probably no longer include these in the list of taps

**Comment by geerlingguy** [comment]
Please see #41 — I'll make sure tests pass on that PR.
