### ISSUE TITLE
Passwordless sudo for vagrant-hostsupdater does not work with GNU sed

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/mac-dev-playbook#46]
If the user replaces the default BSD `sed` with GNU `sed` through homebrew, the path will be `/usr/local/bin/sed` rather than `/usr/bin/sed`, and therefore the passwordless sudo wont work.

Disclaimer:
Personally it's always been confusing to me when the default tools on macos are a) waaay outdated and b) BSD versions rather than GNU versions which I'm used to from Linux (sed flags being particularly confusing in it's BSD version). To normalize my environments I update all builtin packages and switch to GNU when possible https://github.com/oxyc/mac-dev-playbook/blob/master/config.yml#L31:L68

**Comment by geerlingguy** [comment]
D'oh!
