### ISSUE TITLE
MacOs High Sierra gives problem with Homebrew permissions

### ISSUE THREAD

**Issue by NileshGule** [geerlingguy/mac-dev-playbook#55]
I am running playbook similar to your Mac-dev-playbook. Recently I upgraded to Mac OS High Sierra. Everything was running fine until recently. After the upgrade there is permissions issue which fails the playbook. Attached is the screenshot of the error.

![homebrew error](https://user-images.githubusercontent.com/1298374/32129007-99b9c870-bbb5-11e7-9d75-1d36c0af2b76.png)

Any idea how to resolve this issue?

**Comment by elliotweiser** [comment]
@NileshGule I think that was addressed in couple of recent PRs to the homebrew role. What version are you running?

**Comment by elliotweiser** [comment]
Yeah, I think it was fully fixed as of version 2.3.1 of the homebrew role.

References: 
https://github.com/geerlingguy/ansible-role-homebrew/pull/75
https://github.com/geerlingguy/ansible-role-homebrew/pull/77

**Comment by NileshGule** [comment]
@elliotweiser I am running 2.2.4 version of the role. Will update to the latest version and see how it reacts.

**Comment by NileshGule** [comment]
@elliotweiser thanks fro your help, the role worked fine after the update.
