### ISSUE TITLE
Question: How do you handle python, pip, php, composer installations?

### ISSUE THREAD

**Issue by frob** [geerlingguy/mac-dev-playbook#59]
I noticed that you are installing node and nvm with homebrew. Why not ruby/rbenv python/pip/pipenv, php/composer?

If you are installing these with another method what is it? I know you are saying that you install ansible with pip but your missing the pip installation step. Are you using the built in python/php?

**Comment by oxyc** [comment]
I use a [makefile](https://github.com/oxyc/mac-playbook/blob/master/Makefile) to bootstrap my initial installation. I bet @geerlingguy has the same flow to install pip and ansible

```sh
sudo easy_install pip
sudo pip install ansible
```

I guess this is a personal workflow question for Jeff but for reference, this is what I install:

```yaml
  - python   # Update pre-installed Python 2 to latest version
  - python3  # Install Python 3
  - { name: php72, install_options: "with-pear,without-fpm" }
  - ruby
  - composer
```

**Comment by frob** [comment]
Thanks @oxyc are those installed with homebrew?

**Comment by oxyc** [comment]
> Thanks @oxyc are those installed with homebrew?

Yes, they're in the `homebrew_installed_packages` list

> also, my understanding is that pip shouldn't be run with sudo

I'm mostly going with Ansible's recommendation at http://docs.ansible.com/ansible/latest/intro_installation.html#latest-releases-via-pip

> Readers that use virtualenv can also install Ansible under virtualenv, though we’d recommend to not worry about it and just install Ansible globally.

**Comment by geerlingguy** [comment]
@frob @oxyc - I do pretty much the same, though I just do `php71` for now. Also, `python` now aliases to Python 3.6, so I do `python2` for compatibility reasons... but I'm itching for the day when I can go full on Python 3 everywhere :)

**Comment by frob** [comment]
> but I'm itching for the day when I can go full on Python 3 everywhere :)

I think everyone but Python 2 developers are itching for that day.
