### ISSUE TITLE
Kick off bootstrap with a single shell command

### ISSUE THREAD

**Issue by jessmartin** [geerlingguy/mac-dev-playbook#6]
@geerlingguy Great work on this! :clap: I've been following various "ansible provision my Mac" projects for over a year and this is the simplest, most straightforward yet.

I was digging into the various forks, I came across @siyelo's [fork](https://github.com/siyelo/laptop) that has added an install.sh file that can be [run via curl](https://github.com/siyelo/laptop#fast-install) without having to install anything.

You might consider pulling in the [install.sh](https://github.com/siyelo/laptop/blob/master/install.sh) and adding the Fast Install option. :smile:

**Comment by geerlingguy** [comment]
This is a possibility. As long as I can keep it really simple, it would be a nice addition, so you can literally open up a new laptop and run one command to bootstrap it.

**Comment by dennschu** [comment]
@geerlingguy 

I solved this issue with with Docker as runtime:

- [Install Docker for Mac](https://docs.docker.com/docker-for-mac/install/)
- [Install ansible through `grpn/ansible-silo` container](https://groupon.github.io/ansible-silo/#installation)

```sh
docker run --interactive \
  --tty \
  --rm \
  --volume "$HOME/bin:/silo_install_path" \ 
  grpn/ansible-silo:2.1.1 \
  --install
```

**drawback**
you have to move from hosts local to  remote

**Comment by marchenm** [comment]
```sh
#!/bin/sh
if [ -x "$(command -v pip)" ]; then
  sudo easy_install pip
fi

if [ -x "$(command -v ansible)" ]; then
  sudo pip install ansible
fi 

ansible-playbook main.yml -i inventory -K 
```

**Comment by apmarshall** [comment]
Took what @marchenm provided, added a couple of other details (`keep-alive` for sudo, `xcode-select --install`, and installing the Ansible requirements), and came up with this:

https://github.com/apmarshall/mac-dev-playbook/blob/develop/install.sh

How about that for a simple install script?
