### ISSUE TITLE
how to handle pip and pip3 ?

### ISSUE THREAD

**Issue by maxandersen** [geerlingguy/mac-dev-playbook#78]
seems by default pip_install uses python2.7 - is there a way to say "install with pip3/python3" ?

**Comment by scnewma** [comment]
You can specify the `executable` when you name the pip_package.

```
pip_packages: 
  - { name: "neovim", executable: "pip3" }
```

**Comment by geerlingguy** [comment]
@scnewma's suggestion is correct; note that at some point I may update this to use `pip3` by default... also if you have the system python set to python3/pip3, Ansible's python interpreter may default to `pip3` for the Ansible `pip` module (I think...).
