### ISSUE TITLE
'Install cask apps' task fails when the app exists

### ISSUE THREAD

**Issue by rong0312** [geerlingguy/mac-dev-playbook#80]
Hey,
A screenshot is attached:
![Screen Shot 2020-01-21 at 10 15 48](https://user-images.githubusercontent.com/33253167/72786737-069c5d00-3c37-11ea-9941-a304ae8f8591.png)

This will immediately exit the play and stop it. 
I would expect that the task will skip on 'errors' like those, am I right?

**Comment by aussielunix** [comment]
reported upstream https://github.com/geerlingguy/ansible-role-homebrew/issues/122
I am hitting this issue now too

**Comment by fishd72** [comment]
Were these apps installed outside of the Ansible playbook?

If so, I think this is a known issue [he mentions](https://github.com/geerlingguy/ansible-role-homebrew) ... 

> `homebrew_cask_accept_external_apps: true`
**Default value is false** and would result in interruption of further processing of the whole role (and ansible play) in case any app given in homebrew_cask_apps is already installed without cask. Good for a tightly managed system.

I'm able to run the playbook on a virgin system multiple times, and the homebrew stuff seems to install the apps ok, then skip over them the next time as expected.

Maybe try setting the above in your config?
