### ISSUE TITLE
ERROR! Syntax Error while loading YAML.

### ISSUE THREAD

**Issue by syther101** [geerlingguy/mac-dev-playbook#83]
Been a while since I've run this playbook. But setting up a new machine today I hit a problem when running for the first time complaining about a syntax error in the inventory.

I'm not sure if this is ansible now preferring the YAML inventory syntax over INI but adding `-I` to the command seems to have done the trick.

Console output:
```
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [all] *********************************************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************

ERROR! Syntax Error while loading YAML.
  expected '<document start>', but found '<scalar>'

The error appears to be in '/Users/ryanh/Development/Projects/git/mac-dev-playbook/inventory': line 2, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

[localhost]
127.0.0.1
^ here
```

Not sure if I've ever thanked you for this project so thanks @geerlingguy. It's a must for setting up a new dev machine in a reproducible way.

Cheers!
Ryan

**Comment by syther101** [comment]
Oh and If you're busy I can happily submit a simple pull request for the readme :)

**Comment by geerlingguy** [comment]
@syther101 - That's really strange, I haven't had any issues with any recent Ansible versions—that would be a major bug in Ansible if inventory files were not able to be parsed correctly. Can you check what version of Ansible you're running?

Also, what's the exact command you ran that led to that failure? It seems like Ansible might be trying to run your inventory file as a playbook, and that would definitely fail.

**Comment by geerlingguy** [comment]
The command should be:

```
ansible-playbook main.yml -i inventory -K
```

As listed in the README.

**Comment by syther101** [comment]
Wow yep very sorry for that @geerlingguy. I don't know how I ended up running the command without `-i`, but indeed it's right there in the readme too 🤦‍♂️.

Thanks so much for trying to lend a hand regardless of my rookie error :)

**Comment by geerlingguy** [comment]
@syther101 - No problem!
