### ISSUE TITLE
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.

### ISSUE THREAD

**Issue by arnoldasbet** [geerlingguy/mac-dev-playbook#88]
I've got

**config.yml**

```
homebrew_cask_apps:
  - chromedriver
  - docker
  - firefox
  - slack
```

homebrew made some changes
https://github.com/Homebrew/discussions/discussions/340

So I get these errors now

```
TASK [geerlingguy.homebrew : Install configured cask applications.] *********************************************************************************************************************************************************
failed: [127.0.0.1] (item=chromedriver) => {"ansible_loop_var": "item", "changed": false, "item": "chromedriver", "msg": "Error: Calling brew cask install is disabled! Use brew install [--cask] instead."}
failed: [127.0.0.1] (item=docker) => {"ansible_loop_var": "item", "changed": false, "item": "docker", "msg": "Error: Calling brew cask install is disabled! Use brew install [--cask] instead."}
failed: [127.0.0.1] (item=firefox) => {"ansible_loop_var": "item", "changed": false, "item": "firefox", "msg": "Error: Calling brew cask install is disabled! Use brew install [--cask] instead."}
failed: [127.0.0.1] (item=slack) => {"ansible_loop_var": "item", "changed": false, "item": "slack", "msg": "Error: Calling brew cask install is disabled! Use brew install [--cask] instead."}
```

**Comment by roycastro** [comment]
Hi @arnoldasbet, please check [this answer](https://github.com/ansible-collections/community.general/issues/1524#issuecomment-753658167), as it worked for me to avoid those specific errors. Also, they comment that it is already released a version of Ansible (2.10.5) that takes care of that. 👍

**Comment by dspolleke** [comment]
some casks are still not installable. 

for instance google-chrome-canary
not installable via Ansible
https://stackoverflow.com/questions/65508191/cask-google-chrome-canary-is-unavailable
but this solution works from the cli.

**Comment by geerlingguy** [comment]
@dspolleke - I believe that the issue may be fixed in the latest version of Ansible 3.x, as it required some changes to Ansible's homebrew module...

**Comment by geerlingguy** [comment]
See upstream issue: https://github.com/geerlingguy/ansible-role-homebrew/issues/155
