### ISSUE TITLE
npm package installation fails because /usr/local/bin is not in path

### ISSUE THREAD

**Issue by Yannik** [geerlingguy/mac-dev-playbook#89]
Hi,
thanks for providing this role!

Unfortunately I ran into a problem while installing npm packages:
`
failed: [user] (item=gulp) => {"ansible_loop_var": "item", "changed": false, "item": "gulp", "msg": "Failed to find required executable npm in paths: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin"}
`

For some reason, `/usr/local/bin` is not in the `PATH`. When I check the `PATH` in the terminal, it is included and npm works fine.

Here's the (boiled down) config I'm using:

```
homebrew_installed_packages:
  - node

npm_packages:
  - gulp
```

Thanks in advance!

**Comment by Yannik** [comment]
I found this related issue: https://github.com/ansible/ansible/issues/34282

**Comment by Yannik** [comment]
When setting the npm `executable` manually, I run into another issue (similar to https://github.com/ansible/ansible-modules-extras/issues/2128), which seemingly is also caused by the incomplete `PATH`.

I wonder why this is working for you, @geerlingguy ?

**Comment by nathan-sav** [comment]
I don't know why this works for others, but I just ran into this and fixed by putting this into ~/.zshenv
`export PATH="$PATH:/usr/local/bin"`

**Comment by geerlingguy** [comment]
I have a `.zshrc` file in my dotfiles (the default ones installed with this playbook) that overrides the path and ensures all the relevant paths are added. You should make sure that you include the required paths for the things you install in your own `.zshrc` or other sourced files (like it seems you have!).
