### ISSUE TITLE
Lints failing with ansible-lint 5.0.1 due to requirements file format

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/mac-dev-playbook#91]
It looks like if the `requirements.yml` file doesn't have a `roles` key for the roles that need to be installed, no roles are installed and ansible-lint silently fails:

```
 10:14:19 Development/GitHub/mac-dev-playbook 
$ ansible-lint 
Running ansible-galaxy install --roles-path .cache/roles -vr requirements.yml
Running ansible-galaxy collection install -p .cache/collections -vr requirements.yml

 10:14:47 Development/GitHub/mac-dev-playbook 
$ echo $?
1
```

The format of my requirements file was:

```
---
- name: geerlingguy.dotfiles
- name: geerlingguy.homebrew
- name: geerlingguy.mas
```

If I change it to:

```
---
roles:
  - name: geerlingguy.dotfiles
  - name: geerlingguy.homebrew
  - name: geerlingguy.mas
```

Then ansible-lint works.

**Comment by ssbarnea** [comment]
@geerlingguy you failed to mention one essential bit: version of ansible you are running with. Success or failure to run may heavily depend on that. Also be sure you check the exact executable being used, I know for sure that Github gradefuly preinstalled an outdated version of Ansible on its workers, making very easy to endup calling that one.

**Comment by geerlingguy** [comment]
I'm running a `pip install ansible`, which should always install the latest version.

In the job output:

```
Run pip3 install yamllint ansible ansible-lint
Collecting yamllint
  Downloading yamllint-1.26.0-py2.py3-none-any.whl (60 kB)
Collecting ansible
  Downloading ansible-3.0.0.tar.gz (30.8 MB)
```
