### ISSUE TITLE
Brew's core packages not installing

### ISSUE THREAD

**Issue by musayev-io** [geerlingguy/mac-dev-playbook#92]
Not sure what I'm missing, but my Brew core packages are not installing, but Casks are. I just updated `default.config.yml` to match my required packages, so the setup is pretty vanilla. 

Here's a link to the repo: https://github.com/musayev-io/bootstrap-ansible-investigate
The command I'm running is `ansible-playbook main.yml -i inventory -K --tags "homebrew"`. Not that it should matter, but same result when running the basic command: `ansible-playbook main.yml -i inventory --ask-become-pass` 

Attached is the output from CLI.: [cli-output.txt](https://github.com/geerlingguy/mac-dev-playbook/files/6032861/cli-output.txt)

Any guidance is greatly appreciated, thanks!

**Comment by geerlingguy** [comment]
@musayev-io - It seems like that's not a clean fork of this project, and I don't have the time to try to do a diff of that project against this one to see what difference might be causing that problem to happen.

**Comment by geerlingguy** [comment]
Closing unless more info is given; it looks like the data in your configuration might be formatted incorrectly; see the error message:

```
TASK [geerlingguy.homebrew : Install configured cask applications.] ************
fatal: [127.0.0.1]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: None. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
```
