### ISSUE TITLE
Ensure directory tasks hang (for me)

### ISSUE THREAD

**Issue by mathew-fleisch** [geerlingguy/mac-dev-playbook#93]
I tried this out for the first time yesterday, and had to manually create/verify existence of directories and remove those ansible tasks, to get it to work. Have you seen this before? Any advice to what I might be doing wrong would be appreciated. I love the idea, and would love to maintain my macs with this approach. The first task that hangs, and never errors/times out is in the homebrew role, but this happens with all of these types for me:
```# Homebrew setup prerequisites.
- name: Ensure Homebrew parent directory has correct permissions (MacOS >= 10.13).
  file:
    path: "{{ homebrew_prefix }}"
    owner: root
    state: directory
  become: yes
  when: "ansible_distribution_version is version('10.13', '>=')"```

**Comment by elisiano** [comment]
yeah I saw this too but I thought it was something else on my laptop playing interference. Apparently not.

**Comment by mathew-fleisch** [comment]
I ran it again with verbose mode on and this is the output when it hangs (with some bits redacted): 
```
TASK [geerlingguy.homebrew : Ensure Homebrew parent directory has correct permissions (MacOS >= 10.13).] ****************************************************************************************
task path: /Users/username/src/mac-dev-playbook/roles/geerlingguy.homebrew/tasks/main.yml:8
Using module file /Users/username/Library/Python/3.8/lib/python/site-packages/ansible/modules/file.py
Pipelining is enabled.
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: username
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=REDACTED] password:" -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-REDACTED ; /usr/bin/python'"'"' && sleep 0'
```

**Comment by webflo** [comment]
II had the same problem. Disabling SSH pipelining helped. Try to add ```ANSIBLE_SSH_PIPELINING=0 ``` in front of your ansible command.

**Comment by mathew-fleisch** [comment]
> I had the same problem. Disabling SSH pipelining helped. Try to add `ANSIBLE_SSH_PIPELINING=0 ` in front of your ansible command.

This worked for me!!!

**Comment by elisiano** [comment]
@geerlingguy is there any reason not to change the default behavior? https://github.com/geerlingguy/mac-dev-playbook/blob/9bd4b41a2eb7e54ab07249fc102e845b305f1eb7/ansible.cfg#L6

**Comment by geerlingguy** [comment]
@elisiano - Yeah... it doesn't need to be set for local runs; it only helps if you're running over an SSH connection to the Mac (which is not necessarily the default use case here).

**Comment by mathew-fleisch** [comment]
If you don't want to change the default behavior, maybe just call it out in the read-me to set that flag if you're running it locally?

**Comment by elisiano** [comment]
I created a PR (#94) in case this change is acceptable.
