### ISSUE TITLE
Setting this up on a fresh installation of macOS Big Sur

### ISSUE THREAD

**Issue by dwardu89** [geerlingguy/mac-dev-playbook#95]
I tried running this on a fresh installation of macOS Big Sur. However since Python 2.7 is the default version you should add the following instructions (until your dot file kicks in with the correct settings):

1. alias python=python3
2. install pip
3. `export PATH="$HOME/Library/Python/3.8/bin/:$PATH"`
4. install Ansible
....  continue with the steps

Probably the can be put into a script

**Comment by geerlingguy** [comment]
Good idea; I haven't set up a brand new back on Big Sur yet (I did an in-place upgrade on my current Mac), so I haven't had to deal with the Python versioning stuff.

**Comment by dwardu89** [comment]
I had to do it after a massive disaster with my device. I'm currently setting it up.
I realised, you should also consider installing `pyenv` using brew and installing python 3.8.7. By running `pyenv install 3.8.7` from there and setting it as the default version after using `pyenv global 3.8.7` is installed in brew.

**Comment by dspolleke** [comment]
I did a clean (virtual) install as well. Either i am missing steps or there is something wrong. I get "permission denied" on dir_s_mkdir on /usr/local/Caskroom 
and the problem mentioned above. 
and after install i could not re-run anible...

**Comment by dspolleke** [comment]
#!/bin/bash
alias python=python3
pyver=$( python -V | grep Python | awk '{ print substr($2, 1, length($2)-2 )}')
pylatest=$(pyenv install --list | grep -v - | grep -v b | tail -1)

if curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py ;
then
  python get-pip.py
fi

export PATH="$HOME/Library/Python/${pyver}/bin/:$PATH"

xcode-select --install

python -m pip install --user ansible

ansible-galaxy install -r requirements.yml
ansible-playbook main.yml -i inventory --ask-become-pass

pyenv install "${pylatest}"
pyenv global "${pylatest}"

**Comment by StephenBrown2** [comment]
I would suggest a small change to your logic for determining `pylatest`. On my machine, it doesn't exclude the alpha releases of 3.10, so I get:
```sh
❯ pyenv install --list | grep -v - | grep -v b | tail -1
  3.10.0a6
```
Where instead you can exclude a(lpha), b(eta), and (release )c(andidates) with:
```sh
❯ pyenv install --list | grep -Ev '[abc-]' | tail -1
  3.9.2
```

Also, for `pyver`, I wasn't getting expected results because `python -V` was sending it's output to stderr, and once I fixed that, it included a trailing period:
```sh
❯ python -V 2>&1 | awk '{ print substr($2, 1, length($2)-2 )}'
2.7.
```

So, instead, I split the version on ".", and rejoined the first two elements only:
```sh
❯ python -V 2>&1 | awk '/Python/{ split($2, a, "."); print a[1]"."a[2] }'
2.7
```
Works for python3 as well:
```sh
❯ python3 -V 2>&1 | awk '/Python/{ split($2, a, "."); print a[1]"."a[2] }'
3.9
```

**Comment by geerlingguy** [comment]
Fixed via: https://github.com/geerlingguy/mac-dev-playbook/commit/39933d749f60d3bdab5881eddf4af6b57b4ed0a0

I just tested the process I documented [in the README under installation](https://github.com/geerlingguy/mac-dev-playbook#installation) on a brand new M1 MacBook Air with Big Sur, and can confirm it works!
